//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1_BHS_OAS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ga_config")]
        public string GA_Config {
            get {
                return ((string)(this["GA_Config"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data source=filepath;provider=Microsoft.ACE.OLEDB.12.0;extended properties=\'Excel" +
            " 8.0;HDR=No;IMEX=1;\'")]
        public string Read_xls {
            get {
                return ((string)(this["Read_xls"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data source=filepath;provider=Microsoft.ACE.OLEDB.12.0;extended properties=\'Excel" +
            " 8.0;HDR=No;IMEX=0;\'")]
        public string Write_xls {
            get {
                return ((string)(this["Write_xls"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data source=filepath;provider=Microsoft.ACE.OLEDB.12.0;extended properties=\'Excel" +
            " 12.0 Xml;HDR=No;IMEX=1;\'")]
        public string Read_xlsx {
            get {
                return ((string)(this["Read_xlsx"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data source=filepath;provider=Microsoft.ACE.OLEDB.12.0;extended properties=\'Excel" +
            " 12.0 Xml;HDR=No;IMEX=0;\'")]
        public string Write_xlsx {
            get {
                return ((string)(this["Write_xlsx"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int PopulationSize {
            get {
                return ((int)(this["PopulationSize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int Generations {
            get {
                return ((int)(this["Generations"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int StallGenLimit {
            get {
                return ((int)(this["StallGenLimit"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1E-07")]
        public double FitnessLimit {
            get {
                return ((double)(this["FitnessLimit"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public float CrossRate {
            get {
                return ((float)(this["CrossRate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public float MutationRate {
            get {
                return ((float)(this["MutationRate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("selection-roulette")]
        public string SelectFcn {
            get {
                return ((string)(this["SelectFcn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("crossover-twopoint")]
        public string CrossoverFcn {
            get {
                return ((string)(this["CrossoverFcn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("custom_mutationfcn")]
        public string MutatoinFcn {
            get {
                return ((string)(this["MutatoinFcn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.7.229;Initial Catalog=T1_BHS_web;Persist Security Info=True;U" +
            "ser ID=sa;Password=1qaz@WSX")]
        public string T1_BHS_WEB_DB {
            get {
                return ((string)(this["T1_BHS_WEB_DB"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.7.229;Initial Catalog=T1_BHS;Persist Security Info=True;User " +
            "ID=t1bhs;Password=t1bhsdba")]
        public string T1_BHS_DB {
            get {
                return ((string)(this["T1_BHS_DB"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("oas_app")]
        public string OAS_App {
            get {
                return ((string)(this["OAS_App"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbo.OAS_SQL")]
        public string TableName_OAS_SQL {
            get {
                return ((string)(this["TableName_OAS_SQL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM {0} WHERE CODE_ID = \'{1}\'")]
        public string SQLStr_OSA_SQL {
            get {
                return ((string)(this["SQLStr_OSA_SQL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbo.ALL_EXE_CONF")]
        public string TableName_ALL_EXE_CONF {
            get {
                return ((string)(this["TableName_ALL_EXE_CONF"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("U_AllExeConf_1")]
        public string U_AllExeConf_1 {
            get {
                return ((string)(this["U_AllExeConf_1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S_AllExeConf_1")]
        public string S_AllExeConf_1 {
            get {
                return ((string)(this["S_AllExeConf_1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sheet1")]
        public string TableName_XLSX_FlightData {
            get {
                return ((string)(this["TableName_XLSX_FlightData"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S_XLSXFlightData_1")]
        public string S_XLSXFlightData_1 {
            get {
                return ((string)(this["S_XLSXFlightData_1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FlightData.xlsx")]
        public string ReadFileName {
            get {
                return ((string)(this["ReadFileName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FlightResult_{0}.csv")]
        public string SaveFileName {
            get {
                return ((string)(this["SaveFileName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\ASI Project\\T1行李自動分揀系統文件(17E3067A)\\0P_專案程式\\T1BHS_PRJ-OAS\\T1_BHS_OAS-General\\T1" +
            "_BHS_OAS\\_data")]
        public string ReadFileDirectory {
            get {
                return ((string)(this["ReadFileDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\ASI Project\\T1行李自動分揀系統文件(17E3067A)\\0P_專案程式\\T1BHS_PRJ-OAS\\T1_BHS_OAS-General\\T1" +
            "_BHS_OAS\\_result")]
        public string SaveFileDirectory {
            get {
                return ((string)(this["SaveFileDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ws://0.0.0.0:2323")]
        public string WebSocket_IP {
            get {
                return ((string)(this["WebSocket_IP"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20191220")]
        public string Selected_Date {
            get {
                return ((string)(this["Selected_Date"]));
            }
            set {
                this["Selected_Date"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbo.GA_CAROUSEL_TABLE_T1")]
        public string TableName_GA_CAROUSEL_TABLE_T1 {
            get {
                return ((string)(this["TableName_GA_CAROUSEL_TABLE_T1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S_GACarouselTableT1_1")]
        public string S_GACarouselTableT1_1 {
            get {
                return ((string)(this["S_GACarouselTableT1_1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbo.GA_COUNTER_TABLE_T1")]
        public string TableName_GA_COUNTER_TABLE_T1 {
            get {
                return ((string)(this["TableName_GA_COUNTER_TABLE_T1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S_GACounterTableT1_1")]
        public string S_GACounterTableT1_1 {
            get {
                return ((string)(this["S_GACounterTableT1_1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60000")]
        public int HealthCheck_Time {
            get {
                return ((int)(this["HealthCheck_Time"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S_LateralConf_1")]
        public string S_LateralConf_1 {
            get {
                return ((string)(this["S_LateralConf_1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int Timeout_PR {
            get {
                return ((int)(this["Timeout_PR"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SW_ACC {
            get {
                return ((bool)(this["SW_ACC"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SW_RC {
            get {
                return ((bool)(this["SW_RC"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SW_GDC {
            get {
                return ((bool)(this["SW_GDC"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SW_DSC {
            get {
                return ((bool)(this["SW_DSC"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SW_FSC {
            get {
                return ((bool)(this["SW_FSC"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbo.LATERAL_CONF")]
        public string TableName_LATERAL_CONF {
            get {
                return ((string)(this["TableName_LATERAL_CONF"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbo.MAKEUP_ALLOC")]
        public string TableName_MAKEUP_ALLOC {
            get {
                return ((string)(this["TableName_MAKEUP_ALLOC"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S_MakeupAlloc_1")]
        public string S_MakeupAlloc_1 {
            get {
                return ((string)(this["S_MakeupAlloc_1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public uint MsgRQ_Retry {
            get {
                return ((uint)(this["MsgRQ_Retry"]));
            }
        }
    }
}
